// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-workers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_workers_default = defineTool({
  name: "list_workers",
  title: "List workers",
  description: "List workers for the signed-in user with their daily wage and worker code.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("workers").select("id, worker_code, name, phone, daily_wage, site_name, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { workers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-attendance.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_attendance_default = defineTool2({
  name: "get_attendance",
  title: "Get attendance",
  description: "Get attendance records for a date range (YYYY-MM-DD). Optionally filter by worker_id.",
  inputSchema: {
    from_date: z2.string().describe("Start date, inclusive. Format YYYY-MM-DD."),
    to_date: z2.string().describe("End date, inclusive. Format YYYY-MM-DD."),
    worker_id: z2.string().optional().describe("Optional worker UUID to filter.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date, worker_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser2(ctx).from("attendance").select("id, worker_id, date, status, overtime_hours, site_name, notes").gte("date", from_date).lte("date", to_date).order("date", { ascending: false });
    if (worker_id) q = q.eq("worker_id", worker_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { attendance: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-cashbook.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_cashbook_default = defineTool3({
  name: "get_cashbook",
  title: "Get cashbook entries",
  description: "List cashbook (income/expense) entries within a date range.",
  inputSchema: {
    from_date: z3.string().describe("Start date YYYY-MM-DD."),
    to_date: z3.string().describe("End date YYYY-MM-DD."),
    limit: z3.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("cashbook").select("*").gte("date", from_date).lte("date", to_date).order("date", { ascending: false }).limit(limit ?? 100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let income = 0, expense = 0;
    for (const row of data ?? []) {
      const amt = Number(row.amount ?? 0);
      if (row.type === "income") income += amt;
      else expense += amt;
    }
    return {
      content: [{ type: "text", text: JSON.stringify({ income, expense, balance: income - expense, entries: data }) }],
      structuredContent: { income, expense, balance: income - expense, entries: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "uwyoyxdhvgkicinouong";
var mcp_default = defineMcp({
  name: "ashapura-samrat-mcp",
  title: "Ashapura Samrat MCP",
  version: "0.1.0",
  instructions: "Tools for the Ashapura Samrat construction management app. Read workers, attendance, and cashbook entries for the signed-in user. Dates are YYYY-MM-DD in Asia/Kolkata.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_workers_default, get_attendance_default, get_cashbook_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
